## Shared theme settings used by Neovim and other applications.
[theme]
scheme = "nightfox"
style = "nightfox"
background = "dark"

[theme.color]
base = "#111a18"
mantle = "#0b1210"
surface = "#202d29"
text = "#d3dfd7"
subtext = "#91a69a"
red = "#c47f7f"
green = "#8fb59a"
yellow = "#b5aa7a"
blue = "#82aeba"
mauve = "#9e9bb2"

[theme.layout]
line_numbers = true
relative_line_numbers = true
wrap = false
sign_column = "yes"
color_column = 100
scrolloff = 10
cmdheight = 1
laststatus = 3

[theme.layout.indent]
tabstop = 2
shiftwidth = 2
softtabstop = 2
expandtab = true
smartindent = true
