## Shared theme settings used by Neovim and other applications.
[theme]
scheme = "nightfox"
style = "nightfox"
background = "dark"

[theme.color]
base = "#151a1d"
mantle = "#101416"
surface = "#1d2528"
text = "#c8d2cc"
subtext = "#899b92"
red = "#bd7474"
green = "#78977a"
yellow = "#b9a477"
blue = "#7295a3"
mauve = "#9d8eaa"

[theme.layout]
line_numbers = true
relative_line_numbers = true
wrap = false
sign_column = "yes"
color_column = 100
scrolloff = 10
cmdheight = 1
laststatus = 3

[theme.layout.indent]
tabstop = 2
shiftwidth = 2
softtabstop = 2
expandtab = true
smartindent = true
